# Site settings
keywords: Food,Basketball,Programe Design,Travel
author: VinceLai
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
title: My title
description:  For me description